rock:
  select: ['[r]ock', r]
  wins_against: [scissors, lizard]
  verbs: [breaks, crushes]
paper:
  select: ['[p]aper', p]
  wins_against: [rock, spock]
  verbs: [covers, disproves]
scissors:
  select: ['[s]cissors', s]
  wins_against: [paper, lizard]
  verbs: [cuts, decapitates]
lizard:
  select: ['[l]izard', l]
  wins_against: [paper, spock]
  verbs: [eats, poisons]
spock:
  select: ['sp[o]ck', o]
  wins_against: [scissors, rock]
  verbs: [smashes, vaporizes]